DROP DATABASE IF EXISTS gestaofuncionarios;

CREATE DATABASE gestaofuncionarios;

CREATE SCHEMA SGF;

CREATE TABLE SGF.TB_FUNCIONARIO (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(50) NOT NULL,
  designacao VARCHAR(30) NOT NULL,
  salario NUMERIC(8,2) NOT NULL,
  telefone VARCHAR(15) NOT NULL,
  endereco VARCHAR(200) NOT NULL
);
